# Generated by Django 4.1.2 on 2022-10-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VacanteServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', max_length=50)),
                ('empresa', models.CharField(db_column='empresa', max_length=70)),
                ('tipo_vacante', models.CharField(choices=[('TRABAJO', 'De Trabajo'), ('SS', 'Servicio Social'), ('PP', 'Prácticas Profesionales')], db_column='tipo_de_vacante', default='JANUARY', max_length=30)),
                ('carrera', models.CharField(db_column='carrera', max_length=5)),
                ('grado_minimo', models.CharField(db_column='grado_minimo', max_length=20)),
                ('descripcion', models.TextField(db_column='descripcion')),
                ('responsabilidades', models.TextField(db_column='responsabilidades')),
                ('requerimientos', models.TextField(db_column='requerimientos')),
            ],
            options={
                'verbose_name': 'Vacante de Servicio',
                'verbose_name_plural': 'Vacantes de Servicio',
                'db_table': 'VacanteServicio',
                'default_permissions': (),
            },
        ),
    ]
