# Generated by Django 4.1.2 on 2022-10-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacanteservicio',
            name='contacto',
            field=models.CharField(db_column='contacto', default='Sin Contacto', max_length=70),
        ),
    ]
